---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: nimblechat
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: nimblechat
        tier: frontend
    spec:
      containers:
        - name: client
          image: "dichlorodiphen/client"
          resources:
            limits:
              memory: 512Mi
              cpu: 1
          ports:
            - name: http
              containerPort: 3000
