---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: chatapp
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: chatapp
        tier: backend
    spec:
      containers:
        - name: server
          image: "dichlorodiphen/server"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
          ports:
            - name: http
              containerPort: 8000
