apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: nimble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimble
      tier: db
  template:
    metadata:
      labels:
        app: nimble
        tier: db
    spec:
      containers:
        - name: mongo
          image: mongo
          args: ["--dbpath", "/data/db"]
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          volumeMounts:
            - name: "mongo-data"
              mountPath: "/data/db"
          resources:
            limits:
              memory: "512Mi"
              cpu: 1
          ports:
            - containerPort: 5000
      volumes:
        - name: "mongo-data"
          persistentVolumeClaim:
            claimName: "db-pvc"
